### ISSUE TITLE
Tetris: High Scores Can't Be Generated without Existing Document

### ISSUE THREAD

**Issue by oconnetf** [RusticiSoftware/TinCan_Prototypes#37]
Because we rely on an Activity Profile document for recording of high scores, there's a problem using high scores if no document exists because of this condition:

    if (doc == null) {
        throw new NotFoundException(documentContext + ": " + documentId);
    }

**Comment by bscSCORM** [comment]
The line @oconnetf mentions above is the server-side code which is causing `404` to be returned (correctly in the case of a missing document). What's needed here is for this prototype to respond to the missing document by adding a new document, most likely.

**Comment by oconnetf** [comment]
This turned out to have been a side effect of a recent launch permissions assumption in Engine/Cloud. The prototype was not at fault.
