### ISSUE TITLE
tincan.js nor build system not found

### ISSUE THREAD

**Issue by garajo** [RusticiSoftware/TinCan_Prototypes#44]
I've cloned the repo and started an http server for the folder. But I get a 404 for this file. https://github.com/RusticiSoftware/TinCan_Prototypes/blob/master/index.html#L78 

I looked for a build system/scripts, but could not find any. For now, I'm cloning and copying this folder https://github.com/RusticiSoftware/TinCanJS/tree/master/build

**Comment by brianjmiller** [comment]
Did you `git submodule update --init --recursive` after clone?

**Comment by garajo** [comment]
I missed that. Thanks @brianjmiller
