### ISSUE TITLE
Required header X-Experience-API-Version to GET statements

### ISSUE THREAD

**Issue by garajo** [RusticiSoftware/TinCan_Prototypes#45]
I don't know if this is a bug or just requires more documentation. I was getting `{"statements":[]}`, unless headers `X-Experience-API-Version: 1.0.0` was included. If it's documentation that's needed I'm happy to do a PR given some guidance.

![screenshot from 2017-05-02 11 48 59](https://cloud.githubusercontent.com/assets/2825366/25634074/2c1b63a0-2f2e-11e7-9ae1-e76fd1d9cdc3.png)

![screenshot from 2017-05-02 11 52 57](https://cloud.githubusercontent.com/assets/2825366/25634080/2ed1eb8c-2f2e-11e7-84c4-083c4e62e69c.png)

**Comment by garajo** [comment]
I just realized this could be an issue with cloud.scorm.com, and maybe this issue would be better elsewhere.

**Comment by brianjmiller** [comment]
It isn't really a bug. When the `X-Experience-API-Version` header is not in the request then the LRS assumes it is a 0.9 version request, and will return an empty statements array unless you have 0.9 statements in that endpoint and available to that credential. That is, assuming the LRS supports 0.9 requests at all.

**Comment by garajo** [comment]
That makes sense, but is not intuitive. It should be documented or the tagged with the version, as it can be confusing thinking no statements are being stored.
